function timeOCD = import_ocd(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TIMEOCD = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  TIMEOCD = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  timeOCD = importfile("/home/marc/git_personal/colab_mpc/ColaborativeMPC-/experiments/test-bench/catkin_mrs/src/colab_mpc/src/NonLinearControllerObject/dist/time_OCD.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Jun-2023 13:01:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", ","];

% Specify column names and types
opts.VariableNames = "e00";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
timeOCD = readtable(filename, opts);

%% Convert to output type
timeOCD = table2array(timeOCD);
end